# translation of src_debug_server.po to French
# Module src_debug_server translation file for language=en
# Copyright (C) 2003 Archaeopteryx Software, Inc.
# Wing Python IDE -- wingware.com
# Encolpe DEGOUTE <encolpe.degoute@free.fr>, 2004.
#
msgid ""
msgstr ""
"Project-Id-Version: src_debug_server\n"
"POT-Creation-Date: 2020-05-13 12:04+EDT\n"
"PO-Revision-Date: 2018-08-25 23:20+0200\n"
"Last-Translator: Jean Sanchez <js.fr@protonmail.ch>\n"
"Language-Team: French\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.4\n"
"X-Generator: Poedit 2.1.1\n"

#: src/debug/tserver/abstract.py:346
msgid "Wing Debug Log File\n"
msgstr "Fichier de log de débogage de Wing\n"

#: src/debug/tserver/abstract.py:347
msgid "This file can be used to diagnose problems in debugger internals\n"
msgstr ""
"Ce file peut être utilisé pour diagnostiquer les problèmes dans les routines "
"du débogueur\n"

#: src/debug/tserver/abstract.py:348
msgid "For help, contact support@wingware.com\n"
msgstr "Pour de l'aide, contactez support@wingware.com\n"

#: src/debug/tserver/abstract.py:353
msgid "Warning:  Log file does not exist:\n"
msgstr "Avertissement : Le fichier de log n'existe pas :\n"

#: src/debug/tserver/abstract.py:355
msgid "Warning:  and could not be created; logging disabled\n"
msgstr "Avertissement : et ne peut pas être créé. Enregistrement désactivé.\n"

#: src/debug/tserver/abstract.py:358
msgid "Warning:  Log file is not a file:\n"
msgstr "Avertissement : Le fichier de log n'est pas un fichier :\n"

#: src/debug/tserver/abstract.py:360
msgid "Warning:  Logging disabled\n"
msgstr "Avertissement : Logging désactivé\n"

#: src/debug/tserver/dbginspect.py:58 src/debug/tserver/dbgserver.py:3060
#: src/debug/tserver/dbgutils.py:489 src/debug/tserver/dbgutils.py:510
msgid "(truncated)"
msgstr "(tronqué)"

#: src/debug/tserver/dbginspect.py:929 src/debug/tserver/dbgutils.py:499
#: src/debug/tserver/dbgutils.py:520 src/debug/tserver/dbgutils.py:3156
msgid "<opaque "
msgstr "<opaque "

#: src/debug/tserver/dbgserver.py:1291
msgid "<module>"
msgstr "<module>"

#: src/debug/tserver/dbgserver.py:1433
msgid "<error evaluating>"
msgstr "<erreur durant l'évaluation>"

#: src/debug/tserver/dbgserver.py:2029 src/debug/tserver/dbgserver.py:2065
msgid "<thread %i is running>"
msgstr "<la tâche %i est en cours>"

#: src/debug/tserver/dbgserver.py:2032 src/debug/tserver/dbgserver.py:2068
msgid "<invalid thread id %s or stack index %s>"
msgstr "<id de tâche %s ou index de pile %s invalide>"

#: src/debug/tserver/dbgserver.py:2034 src/debug/tserver/dbgserver.py:2070
msgid "<invalid stack frame>"
msgstr "<élément de pile invalide>"

#: src/debug/tserver/dbgserver.py:2098 src/debug/tserver/dbgserver.py:2127
msgid "<sys.modules does not exist>"
msgstr "<sys.modules n'existe pas>"

#: src/debug/tserver/dbgserver.py:2101 src/debug/tserver/dbgserver.py:2132
msgid "<error accessing sys.modules>"
msgstr "<erreur en accédant à sys.modules>"

#: src/debug/tserver/dbgserver.py:2129
msgid "<no longer exists"
msgstr "<n'existe plus"

#: src/debug/tserver/dbgserver.py:2177 src/debug/tserver/dbgserver.py:2230
msgid "<no longer exists>"
msgstr "<n'existe plus>"

#: src/debug/tserver/dbgserver.py:2208 src/debug/tserver/dbgserver.py:4518
msgid "<parent too large>"
msgstr "<parent trop large>"

#: src/debug/tserver/dbgserver.py:2210 src/debug/tserver/dbgserver.py:4520
msgid "<invalid parent type>"
msgstr "<type de parent invalide>"

#: src/debug/tserver/dbgserver.py:2220 src/debug/tserver/dbgserver.py:2689
msgid "<value not found>"
msgstr "<valuer non trouvée>"

#: src/debug/tserver/dbgserver.py:2677
msgid "<thread is running>"
msgstr "<tâche en cours>"

#: src/debug/tserver/dbgserver.py:2679
msgid "<invalid context>"
msgstr "<contexte invalide>"

#: src/debug/tserver/dbgserver.py:4526
msgid "<invalid path %s at pos=%i>"
msgstr "<chemin %s invalide à la position=%i>"

#: src/debug/tserver/dbgutils.py:151
msgid "<undefined>"
msgstr "<indéfini>"

#: src/debug/tserver/dbgutils.py:167
msgid "at"
msgstr "à"

#: src/debug/tserver/dbgutils.py:177
msgid "len=%s>"
msgstr ""

#: src/debug/tserver/dbgutils.py:187 src/debug/tserver/dbgutils.py:2649
#, fuzzy
msgid "<error handling value>"
msgstr "<erreur durant l'évaluation>"

#: src/debug/tserver/dbgutils.py:189
msgid "<timeout>"
msgstr ""

#: src/debug/tserver/dbgutils.py:197
msgid "<huge "
msgstr ""

#: src/debug/tserver/dbgutils.py:217
msgid "<long "
msgstr ""

#: src/debug/tserver/dbgutils.py:234
msgid "<opaque"
msgstr "<opaque"

#: src/debug/tserver/dbgutils.py:512
msgid "<huge %s at %s; len=%i>"
msgstr "<énorme %s à %s ; longueur=%i>"

#: src/debug/tserver/dbgutils.py:726 src/debug/tserver/dbgutils.py:738
msgid ", pos "
msgstr ", position "

#: src/debug/tserver/dbgutils.py:742
msgid ", line "
msgstr ", ligne "

#: src/debug/tserver/dbgutils.py:744
msgid "SyntaxError: "
msgstr "Erreur de syntaxe : "

#: src/debug/tserver/dbgutils.py:772
msgid "Error"
msgstr "Erreur"

#: src/debug/tserver/dbgutils.py:782
msgid "Error: Wing was unable to pack up an exception message"
msgstr "Erreur : Wing n'a pas été capable de générer un message d'exception"

#: src/debug/tserver/dbgutils.py:3518 src/debug/tserver/dbgutils.py:3534
msgid "Key"
msgstr ""

#: src/debug/tserver/dbgutils.py:3518 src/debug/tserver/dbgutils.py:3534
msgid "Value"
msgstr "Valeur"

#: src/debug/tserver/dbgutils.py:3529 src/debug/tserver/dbgutils.py:3556
msgid "Item"
msgstr ""

#: src/debug/tserver/netserver.py:472
msgid "Redirected I/O failed on closed debug connection"
msgstr ""
"La redirection des E/S a échoué lors de la fermeture de la connexion de "
"débogage"

#: src/debug/tserver/netserver.py:635
msgid "EOF when reading a line"
msgstr "EOF lors de la lecture d'une ligne"

#: src/debug/tserver/netserver.py:1209
msgid "(unavailable)"
msgstr "(indisponible)"

#: src/debug/tserver/netserver.py:1472
msgid "[omitting some output]"
msgstr "[omet quelques sorties]"

#: src/debug/tserver/startdebug.py:205 src/debug/tserver/startdebug.py:390
#, fuzzy
msgid "wingdb.py: Error: Debug file does not exist:"
msgstr "Avertissement : Le fichier de log n'existe pas :\n"

#: src/debug/tserver/startdebug.py:209 src/debug/tserver/startdebug.py:394
#, fuzzy
msgid "wingdb.py: Error: Debug file is not a file:"
msgstr "Avertissement : Le fichier de log n'est pas un fichier :\n"

#: src/debug/tserver/startdebug.py:443
msgid "Network peer is "
msgstr ""

#: src/debug/tserver/startdebug.py:444
msgid "Attach port = "
msgstr ""

#: src/debug/tserver/startdebug.py:445
msgid "Initial stop = "
msgstr ""

#: src/debug/tserver/startdebug.py:459
msgid "wingdb.py: Could not create debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:481
msgid "wingdb.py: Running %s"
msgstr ""

#: src/debug/tserver/startdebug.py:492 src/debug/tserver/startdebug.py:519
msgid "wingdb.py: Server exiting abnormally on exception"
msgstr ""

#: src/debug/tserver/startdebug.py:681
msgid "wingdb.py: Error: Failed to start the debug server"
msgstr ""

#: src/debug/tserver/startdebug.py:682
msgid "wingdb.py: Error: You may be running an unsupported version of Python"
msgstr ""

#: src/debug/tserver/startdebug.py:683
msgid "wingdb.py: Python version = %s"
msgstr ""

#: src/debug/tserver/startdebug.py:768 src/debug/tserver/startdebug.py:770
msgid "-- Type return or enter to exit --\n"
msgstr ""

#~ msgid "<unknown type>"
#~ msgstr "<type inconnu>"

#~ msgid "Value too large to evaluate: "
#~ msgstr "Value trop grande pour être évaluée : "

#~ msgid "<invalid path registration>"
#~ msgstr "<enregistrement de chemin invalide>"

#~ msgid "Function"
#~ msgstr "Fonction"

#~ msgid "Method"
#~ msgstr "Méthode"

#, fuzzy
#~ msgid "Could not execute because an error occurred:\n"
#~ msgstr ""
#~ "Impossible de lancer le programme car il y a eu une erreur:\n"
#~ "\n"

#~ msgid "Error: Runtime exception occurred"
#~ msgstr "Erreur: Obtention d'une erreur d'exécution"

#~ msgid "Default User"
#~ msgstr "Utilisateur par défaut"
